name: CI

on:
  pull_request:
    branches:
      - "main"

env:
  CARGO_TERM_COLOR: always

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.85.1
      - name: Install cargo audit
        run: cargo install cargo-audit
      - run: cargo audit
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.85.1
      - name: Install cargo clippy
        run: rustup component add clippy --toolchain=1.85.1
      - run: cargo clippy --all-features
